// ─────────────────────────────────────────────
// SkillSnap — Mock Users
// Replace with userService.getUser(id) API calls
// ─────────────────────────────────────────────
import type { User } from "@/types";

export const MOCK_CURRENT_USER: User = {
  id: "user_me",
  username: "@Marcus_Cuts",
  displayName: "Marcus Thompson",
  avatarGradient: "linear-gradient(135deg, #667eea, #764ba2)",
  avatarInitial: "M",
  location: "Liverpool, NSW",
  bio: "Professional barber with 8+ years experience. Specialising in fades, skin fades & modern cuts.",
  skill: "Barber",
  isVerified: true,
  jobsDone: 650,
  happyPercent: 97,
  ratingCount: 412,
  followers: 1200,
  following: 234,
  postCount: 47,
  isClient: false,
  distanceKm: 1,
};

export const MOCK_USERS: User[] = [
  MOCK_CURRENT_USER,
  {
    id: "user_priya",
    username: "@PriyaGlam",
    displayName: "Priya Kaur",
    avatarGradient: "linear-gradient(135deg, #f093fb, #f5576c)",
    avatarInitial: "P",
    location: "Parramatta, NSW",
    bio: "Bridal & event makeup artist. Soft glam to full editorial — every face tells a story.",
    skill: "Makeup Artist",
    isVerified: true,
    jobsDone: 83,
    happyPercent: 94,
    ratingCount: 57,
    followers: 5100,
    following: 190,
    postCount: 62,
    isClient: false,
    distanceKm: 3,
  },
  {
    id: "user_jake",
    username: "@JakeTheTiler",
    displayName: "Jake Richardson",
    avatarGradient: "linear-gradient(135deg, #4facfe, #00f2fe)",
    avatarInitial: "J",
    location: "Penrith, NSW",
    bio: "Qualified tiler with 12 years on the tools. Bathrooms, kitchens, outdoor areas.",
    skill: "Tiler",
    isVerified: false,
    jobsDone: 29,
    happyPercent: 90,
    ratingCount: 21,
    followers: 1800,
    following: 112,
    postCount: 34,
    isClient: false,
    distanceKm: 8,
  },
  {
    id: "user_sam",
    username: "@SamFitPro",
    displayName: "Sam Williams",
    avatarGradient: "linear-gradient(135deg, #43e97b, #38f9d7)",
    avatarInitial: "S",
    location: "Campbelltown, NSW",
    bio: "Personal trainer & nutrition coach. Online & in-person. DM for a free consult.",
    skill: "Fitness / PT",
    isVerified: true,
    jobsDone: 61,
    happyPercent: 98,
    ratingCount: 44,
    followers: 3400,
    following: 220,
    postCount: 58,
    isClient: false,
    distanceKm: 12,
  },
  {
    id: "user_ana",
    username: "@AnaPristineClean",
    displayName: "Ana Martinez",
    avatarGradient: "linear-gradient(135deg, #fa709a, #fee140)",
    avatarInitial: "A",
    location: "Bankstown, NSW",
    bio: "Professional cleaner for residential & commercial spaces. Eco-friendly products.",
    skill: "Cleaning",
    isVerified: false,
    jobsDone: 38,
    happyPercent: 92,
    ratingCount: 26,
    followers: 940,
    following: 78,
    postCount: 21,
    isClient: false,
    distanceKm: 5,
  },
  {
    id: "user_leo",
    username: "@LeoCuts",
    displayName: "Leo Park",
    avatarGradient: "linear-gradient(135deg, #a18cd1, #fbc2eb)",
    avatarInitial: "L",
    location: "Fairfield, NSW",
    bio: "Barber — clean fades, fresh lineups. Walk-ins welcome most days.",
    skill: "Barber",
    isVerified: false,
    jobsDone: 12,
    happyPercent: 83,
    ratingCount: 9,
    followers: 620,
    following: 95,
    postCount: 15,
    isClient: false,
    distanceKm: 2,
  },
  {
    id: "user_jordan",
    username: "@jordan_lee",
    displayName: "Jordan Lee",
    avatarGradient: "linear-gradient(135deg, #43e97b, #38f9d7)",
    avatarInitial: "J",
    location: "Liverpool, NSW",
    bio: "Love discovering talented locals. Always looking for quality tradies and stylists in the area.",
    skill: null,
    isVerified: false,
    jobsDone: 0,
    happyPercent: 0,
    ratingCount: 0,
    followers: 12,
    following: 89,
    postCount: 0,
    isClient: true,
    distanceKm: 1,
  },
];

export function getUserById(id: string): User | undefined {
  return MOCK_USERS.find((u) => u.id === id);
}
