"use client";
import { ArrowLeft } from "lucide-react";
import type { Screen } from "@/types";

interface TermsScreenProps {
  onNavigate: (s: Screen) => void;
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mb-6">
      <h2 className="font-bold text-[#1a1a1a] text-sm mb-2">{title}</h2>
      <div className="text-sm text-[#7a7570] leading-relaxed space-y-2">{children}</div>
    </div>
  );
}

export default function TermsScreen({ onNavigate }: TermsScreenProps) {
  return (
    <div className="flex flex-col min-h-screen bg-[#f8f7f5]">
      <header className="sticky top-0 z-40 bg-white/95 backdrop-blur-sm border-b border-[#e8e4df] flex items-center gap-3 px-4 h-14">
        <button onClick={() => onNavigate("settings")} className="text-[#7a7570]">
          <ArrowLeft size={20} />
        </button>
        <h1 className="font-bold text-base text-[#1a1a1a] flex-1">Terms & Privacy Policy</h1>
      </header>

      <div className="flex-1 overflow-y-auto no-scrollbar px-5 py-6">
        <p className="text-xs text-[#b0aaa5] mb-6">Last updated: May 2025</p>

        <Section title="1. About SkillSnap">
          <p>SkillSnap is an Australian platform operated by SkillSnap Pty Ltd ("we", "us", "our") that connects skilled professionals with local clients through video portfolios. By creating an account or using SkillSnap, you agree to these Terms and our Privacy Policy.</p>
          <p>SkillSnap is intended for users aged 18 and over. By using the platform you confirm you meet this requirement.</p>
        </Section>

        <Section title="2. Using SkillSnap">
          <p>You may use SkillSnap to showcase your skills, discover local professionals, and connect with clients or workers. You agree not to:</p>
          <ul className="list-disc pl-4 space-y-1">
            <li>Post false, misleading, or fraudulent information</li>
            <li>Harass, abuse, or threaten other users</li>
            <li>Upload content that infringes third-party intellectual property rights</li>
            <li>Use the platform for spam, advertising outside of your own profile, or illegal activity</li>
            <li>Attempt to reverse-engineer, scrape, or disrupt the service</li>
          </ul>
          <p>We reserve the right to suspend or terminate accounts that violate these terms without notice.</p>
        </Section>

        <Section title="3. Your Content">
          <p>You retain ownership of all photos, videos, and text you upload to SkillSnap. By posting content you grant SkillSnap a non-exclusive, royalty-free licence to display and distribute that content within the platform for the purpose of operating the service.</p>
          <p>You are solely responsible for the content you post. Do not upload content that is defamatory, explicit, or violates any applicable law.</p>
          <p>You can delete your posts at any time from your profile. Deleted content is removed from public view immediately and purged from our servers within 30 days.</p>
        </Section>

        <Section title="4. Privacy">
          <p>We collect the information you provide when registering (name, email, profile photo) and information generated by your use of the platform (posts, messages, location when set by you).</p>
          <p>We use this information to operate SkillSnap, personalise your experience, and send service-related notifications. We do not sell your personal data to third parties.</p>
          <p>Location data is only used to show you nearby professionals. It is stored only while you have location enabled and is never shared with other users without your consent.</p>
          <p>Messages sent through SkillSnap are stored on our servers to enable the messaging feature. We do not read private messages except where required by law or to investigate reported abuse.</p>
          <p>We use Supabase (data storage), Vercel (hosting), and Google (authentication) as service providers. Each operates under their own privacy policies.</p>
          <p>To request deletion of your account and data, use Settings → Delete Account or contact us at hello@skillsnap.com.au.</p>
        </Section>

        <Section title="5. Payments & Pro Features">
          <p>The core SkillSnap platform is free to use for both clients and professionals. A Pro subscription tier is planned for future release and will be subject to separate pricing terms published at that time.</p>
          <p>SkillSnap does not process payments between clients and professionals. Any financial arrangements are made directly between the parties and SkillSnap is not responsible for disputes arising from those transactions.</p>
        </Section>

        <Section title="6. Disclaimers & Liability">
          <p>SkillSnap provides a platform for users to connect. We do not verify the qualifications, licences, or quality of work of professionals listed on the platform. You are responsible for conducting your own due diligence before engaging any professional.</p>
          <p>To the maximum extent permitted by Australian law, SkillSnap is not liable for any direct, indirect, or consequential loss arising from your use of the platform or your interactions with other users.</p>
          <p>The platform is provided "as is" without warranties of any kind. We will make reasonable efforts to keep the service available but do not guarantee uninterrupted access.</p>
        </Section>

        <Section title="7. Changes to These Terms">
          <p>We may update these Terms from time to time. If we make material changes we will notify you via email or an in-app notice. Continued use of SkillSnap after changes take effect constitutes acceptance of the revised Terms.</p>
        </Section>

        <Section title="8. Contact">
          <p>If you have questions about these Terms or our Privacy Policy, please contact us:</p>
          <p className="font-semibold text-[#6c47ff]">hello@skillsnap.com.au</p>
          <p>SkillSnap Pty Ltd · Sydney, NSW, Australia</p>
        </Section>

        <div className="mt-4 mb-8 rounded-2xl p-4 text-center" style={{ background: "linear-gradient(135deg,#ede9fe,#f5f3ff)", border: "1.5px solid rgba(108,71,255,0.15)" }}>
          <p className="text-xs text-[#7a7570]">Questions? We're happy to help.</p>
          <button
            onClick={() => onNavigate("contact")}
            className="mt-2 px-5 py-2 rounded-xl font-bold text-sm text-white"
            style={{ background: "linear-gradient(135deg,#6c47ff,#8b6af5)" }}
          >
            Contact Us
          </button>
        </div>
      </div>
    </div>
  );
}
